name: gradle-build-actions-workflow
on:
  push:
    # # Sequence of patterns matched against refs/tags
    # tags:
    #   - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
permissions:
    contents: write
    
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: chmod ./gradlew
        if: ${{ matrix.os != 'windows-latest' }}
        shell: bash
        run: sudo chmod +x ./gradlew
        
      - name: Build with Gradle
        if: ${{ matrix.os != 'windows-latest' }}
        run: ./gradlew build
        
      - name: Build with Gradle
        if: ${{ matrix.os == 'windows-latest' }}
        run: ./gradlew.bat build
        
      - working-directory: app/build
        shell: bash
        run: ls -R
      
      # - name: Archive Release
      #   uses: thedoctor0/zip-release@master
      #   with:
      #     type: 'zip'
      #     path: ${{ github.event.repository.name }}*
      #     filename: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip"
          
      # - name: Release prebuilt
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip"
      #     allowUpdates: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
